name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-deno-env

      - run: deno install --frozen
      - run: deno task prepare
      - run: deno task lint
      - run: deno task check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-deno-env

      - run: deno install --frozen
      - run: deno x npm:playwright install --with-deps chromium
      - run: deno task prepare
      - run: deno task test:unit -- --run

#  e2e-tests:
#    name: E2E Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - uses: ./.github/actions/setup-deno-env
#
#      - run: deno install --frozen
#      - run: deno x npm:playwright install --with-deps chromium
#      - run: deno x npm:playwright test
