name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-env

      - run: bun install --frozen-lockfile
      - run: bun run prepare
      - run: bun run lint
      - run: bun run check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun-env

      - run: bun install --frozen-lockfile
      - run: bunx playwright install --with-deps chromium
      - run: bun run prepare
      - run: bun run test:unit -- --run

#  e2e-tests:
#    name: E2E Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - uses: ./.github/actions/setup-bun-env
#
#      - run: bun install --frozen-lockfile
#      - run: bunx playwright install --with-deps chromium
#      - run: bunx playwright test
